# Generated by Django 2.2.28 on 2022-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
