# Generated by Django 2.2.28 on 2022-09-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_emergencycontact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
